### ISSUE TITLE
ASAN: alloc-dealloc-mismatch

### ISSUE THREAD

**Issue by matthiaskrgr** [clangen/musikcube#134]
compile with address sanitizer (I used clang 4.0)
````diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ea99b18..a921b9f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -25,7 +25,7 @@ ExternalProject_Add(taglib
 )
 
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wno-unused-result -Wno-deprecated-declarations")
-set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
+set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g3 -fsanitize=address,undefined")
 set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2")
 
 if (${LINK_STATICALLY} MATCHES "true")
`````
When trying to add files to the library, I sometimes hit a alloc-dealloc-mismatch (operator new [] vs operator delete) 

````
AlsaOut: joining...
AlsaOut: thread finished
AlsaOut: closing device...
AlsaOut: destroyed.
PulseOut: destroy
PulseOut: destructor
=================================================================
==22128==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x7f2aaa7f0800
==22128==AddressSanitizer: while reporting a bug found another one. Ignoring.
    #0 0x8b078b in operator delete(void*) /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:126:3
    #1 0x126af94 in musik::core::IndexerTrack::MetadataWithThumbnail::~MetadataWithThumbnail() /home/matthias/vcs/github/musikcube/src/core/library/track/IndexerTrack.cpp:771:5
    #2 0x1248d8a in musik::core::IndexerTrack::~IndexerTrack() /home/matthias/vcs/github/musikcube/src/core/library/track/IndexerTrack.cpp:74:5
    #3 0x117bb89 in musik::core::Indexer::ReadMetadataFromFile(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/musikcube/src/core/library/Indexer.cpp:403:1
    #4 0x11ff9db in boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::operator()(musik::core::Indexer*, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/boost/bind/mem_fn_template.hpp:280:29
    #5 0x11ff646 in void boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator()<boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&, boost::_bi::list0&, int) /usr/include/boost/bind/bind.hpp:398:9
    #6 0x11fef6d in boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator()() /usr/include/boost/bind/bind.hpp:1222:16
    #7 0x11fec90 in void boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, ...) /usr/include/boost/asio/handler_invoke_hook.hpp:69:3
    #8 0x11fe664 in void boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37:3
    #9 0x11fdd46 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) /usr/include/boost/asio/detail/completion_handler.hpp:68:7
    #10 0x11aab8c in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) /usr/include/boost/asio/detail/task_io_service_operation.hpp:38:5
    #11 0x11a4cb8 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) /usr/include/boost/asio/detail/impl/task_io_service.ipp:372:12
    #12 0x11a257b in boost::asio::detail::task_io_service::run(boost::system::error_code&) /usr/include/boost/asio/detail/impl/task_io_service.ipp:149:10
    #13 0x118e884 in boost::asio::io_service::run() /usr/include/boost/asio/impl/io_service.ipp:59:25
    #14 0x1205ebd in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator()(boost::asio::io_service*) const /usr/include/boost/bind/mem_fn_template.hpp:49:29
    #15 0x1205c5c in unsigned long boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0>(boost::_bi::type<unsigned long>, boost::_mfi::mf0<unsigned long, boost::asio::io_service>&, boost::_bi::list0&, long) /usr/include/boost/bind/bind.hpp:249:16
    #16 0x120596f in boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator()() /usr/include/boost/bind/bind.hpp:1222:16
    #17 0x1205692 in boost::detail::thread_data<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run() /usr/include/boost/thread/detail/thread.hpp:116:17
    #18 0x7f2ada8eb145  (/lib64/libboost_thread.so.1.60.0+0x12145)
    #19 0x7f2ad9c26739 in start_thread (/lib64/libpthread.so.0+0x7739)
    #20 0x7f2ad8847e0e in __GI___clone (/lib64/libc.so.6+0x107e0e)

0x7f2aaa7f0800 is located 0 bytes inside of 163261-byte region [0x7f2aaa7f0800,0x7f2aaa8185bd)
allocated by thread T66 here:
    #0 0x8afccb in operator new[](unsigned long) /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:84:37
    #1 0x124c140 in musik::core::IndexerTrack::SetThumbnail(char const*, long) /home/matthias/vcs/github/musikcube/src/core/library/track/IndexerTrack.cpp:141:45
    #2 0x7f2ac36aa4c3 in TaglibMetadataReader::GetID3v2Tag(char const*, musik::core::sdk::ITrackWriter*) /home/matthias/vcs/github/musikcube/src/plugins/taglib_plugin/TaglibMetadataReader.cpp:358:24
    #3 0x7f2ac369e9c0 in TaglibMetadataReader::Read(char const*, musik::core::sdk::ITrackWriter*) /home/matthias/vcs/github/musikcube/src/plugins/taglib_plugin/TaglibMetadataReader.cpp:131:19
    #4 0x117a7ba in musik::core::Indexer::ReadMetadataFromFile(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/musikcube/src/core/library/Indexer.cpp:342:32
    #5 0x11ff9db in boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::operator()(musik::core::Indexer*, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/boost/bind/mem_fn_template.hpp:280:29
    #6 0x11ff646 in void boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator()<boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&, boost::_bi::list0&, int) /usr/include/boost/bind/bind.hpp:398:9
    #7 0x11fef6d in boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator()() /usr/include/boost/bind/bind.hpp:1222:16
    #8 0x11fec90 in void boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, ...) /usr/include/boost/asio/handler_invoke_hook.hpp:69:3
    #9 0x11fe664 in void boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37:3
    #10 0x11fdd46 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf2<void, musik::core::Indexer, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<musik::core::Indexer*>, boost::_bi::value<boost::filesystem::path>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) /usr/include/boost/asio/detail/completion_handler.hpp:68:7
    #11 0x11aab8c in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) /usr/include/boost/asio/detail/task_io_service_operation.hpp:38:5
    #12 0x11a4cb8 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) /usr/include/boost/asio/detail/impl/task_io_service.ipp:372:12
    #13 0x11a257b in boost::asio::detail::task_io_service::run(boost::system::error_code&) /usr/include/boost/asio/detail/impl/task_io_service.ipp:149:10
    #14 0x118e884 in boost::asio::io_service::run() /usr/include/boost/asio/impl/io_service.ipp:59:25
    #15 0x1205ebd in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator()(boost::asio::io_service*) const /usr/include/boost/bind/mem_fn_template.hpp:49:29
    #16 0x1205c5c in unsigned long boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0>(boost::_bi::type<unsigned long>, boost::_mfi::mf0<unsigned long, boost::asio::io_service>&, boost::_bi::list0&, long) /usr/include/boost/bind/bind.hpp:249:16
    #17 0x120596f in boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator()() /usr/include/boost/bind/bind.hpp:1222:16
    #18 0x1205692 in boost::detail::thread_data<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run() /usr/include/boost/thread/detail/thread.hpp:116:17
    #19 0x7f2ada8eb145  (/lib64/libboost_thread.so.1.60.0+0x12145)

Thread T66 created by T2 here:
    #0 0x86b3c6 in pthread_create /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:305:3
    #1 0x7f2ada8ea498 in boost::thread::start_thread_noexcept() (/lib64/libboost_thread.so.1.60.0+0x11498)
    #2 0x12037fd in boost::thread::thread<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >&>(boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >&) /usr/include/boost/thread/detail/thread.hpp:265:13
    #3 0x118dc50 in boost::thread* boost::thread_group::create_thread<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >(boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >) /usr/include/boost/thread/detail/thread_group.hpp:79:60
    #4 0x11616f2 in musik::core::Indexer::ThreadLoop() /home/matthias/vcs/github/musikcube/src/core/library/Indexer.cpp:541:24
    #5 0x11e24d6 in boost::_mfi::mf0<void, musik::core::Indexer>::operator()(musik::core::Indexer*) const /usr/include/boost/bind/mem_fn_template.hpp:49:29
    #6 0x11e21fb in void boost::_bi::list1<boost::_bi::value<musik::core::Indexer*> >::operator()<boost::_mfi::mf0<void, musik::core::Indexer>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, musik::core::Indexer>&, boost::_bi::list0&, int) /usr/include/boost/bind/bind.hpp:259:9
    #7 0x11e1efd in boost::_bi::bind_t<void, boost::_mfi::mf0<void, musik::core::Indexer>, boost::_bi::list1<boost::_bi::value<musik::core::Indexer*> > >::operator()() /usr/include/boost/bind/bind.hpp:1222:16
    #8 0x11e0412 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, musik::core::Indexer>, boost::_bi::list1<boost::_bi::value<musik::core::Indexer*> > > >::run() /usr/include/boost/thread/detail/thread.hpp:116:17
    #9 0x7f2ada8eb145  (/lib64/libboost_thread.so.1.60.0+0x12145)

Thread T2 created by T0 here:
    #0 0x86b3c6 in pthread_create /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:305:3
    #1 0x7f2ada8ea498 in boost::thread::start_thread_noexcept() (/lib64/libboost_thread.so.1.60.0+0x11498)
    #2 0x1183aed in boost::thread::thread<boost::_bi::bind_t<void, boost::_mfi::mf0<void, musik::core::Indexer>, boost::_bi::list1<boost::_bi::value<musik::core::Indexer*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, musik::core::Indexer>, boost::_bi::list1<boost::_bi::value<musik::core::Indexer*> > >&&) /usr/include/boost/thread/detail/thread.hpp:265:13
    #3 0x115e8cc in musik::core::Indexer::Indexer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/musikcube/src/core/library/Indexer.cpp:118:24
    #4 0xfe3a99 in musik::core::library::LocalLibrary::LocalLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) /home/matthias/vcs/github/musikcube/src/core/library/LocalLibrary.cpp:90:25
    #5 0xfe2761 in musik::core::library::LocalLibrary::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) /home/matthias/vcs/github/musikcube/src/core/library/LocalLibrary.cpp:76:25
    #6 0xfcae81 in musik::core::LibraryFactory::AddLibrary(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/musikcube/src/core/library/LibraryFactory.cpp:72:27
    #7 0xfca6bd in musik::core::LibraryFactory::LibraryFactory() /home/matthias/vcs/github/musikcube/src/core/library/LibraryFactory.cpp:59:15
    #8 0xfc9b1b in musik::core::LibraryFactory::Instance() /home/matthias/vcs/github/musikcube/src/core/library/LibraryFactory.cpp:47:39
    #9 0xfcccb8 in musik::core::LibraryFactory::Libraries() /home/matthias/vcs/github/musikcube/src/core/library/LibraryFactory.cpp:120:12
    #10 0x8b350c in main /home/matthias/vcs/github/musikcube/src/musikcube/Main.cpp:128:27
    #11 0x7f2ad8760400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:126:3 in operator delete(void*)
==22128==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==22128==ABORTING
````

**Comment by matthiaskrgr** [comment]
I can no longer reproduce this ( @ 791f92389262c1dfed94ccd17051540e8d5e78fd )

**Comment by clangen** [comment]
Just FYI, these were still real leaks as of 0.23.0, but would only show up during the indexing process. I went ahead and fixed them for the next release.
